---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: "nginx"
  name: nginx-ingress
  namespace: pr-bot
spec:
  tls:
  - hosts:
    - "prbot.getsilverfin.com"
    secretName: prbot-getsilverfin-com
  rules:
  - host: "prbot.getsilverfin.com"
    http:
      paths:
      - backend:
          serviceName: pr-bot
          servicePort: pr-bot
        path: /
